### ISSUE TITLE
Resolve encoding issues

### ISSUE THREAD

**Issue by ultimate** [ultimate/KaroToolsCollection#98]
❓ ❓❓  **Was mache ich falsch** ❓ ❓ ❓ 

### Senden von ASCII-Nachrichten ist kein Problem (CraZZZy schickt Nachricht an ultimate)

> DEBUG [ForkJoinPool.commonPool-worker-19] 14:23:46 URLLoader.doLoad(226) | POST https://www.karopapier.de/api/messages/1411 -> {"text":"Hallo ultimate, das ist ein API-Test!"}
TRACE [ForkJoinPool.commonPool-worker-19] 14:23:46 URLLoader.doLoad(228) |  - X-Auth-Login = [CraZZZy]
TRACE [ForkJoinPool.commonPool-worker-19] 14:23:46 URLLoader.doLoad(228) |  - X-Auth-Password = [*********]
TRACE [ForkJoinPool.commonPool-worker-19] 14:23:46 URLLoader.doLoad(228) |  - Content-Type = [application/json; charset=utf-8]
DEBUG [ForkJoinPool.commonPool-worker-19] 14:23:46 URLLoader.doLoad(253) | POST https://www.karopapier.de/api/messages/1411 = 200 OK
TRACE [ForkJoinPool.commonPool-worker-19] 14:23:46 URLLoader.doLoad(255) |  - Transfer-Encoding = [chunked]
TRACE [ForkJoinPool.commonPool-worker-19] 14:23:46 URLLoader.doLoad(255) |  - null = [HTTP/1.1 200 OK]
TRACE [ForkJoinPool.commonPool-worker-19] 14:23:46 URLLoader.doLoad(255) |  - sw = [/js/app.js?v=29839b]
TRACE [ForkJoinPool.commonPool-worker-19] 14:23:46 URLLoader.doLoad(255) |  - Server = [nginx/1.14.0 (Ubuntu)]
TRACE [ForkJoinPool.commonPool-worker-19] 14:23:46 URLLoader.doLoad(255) |  - Connection = [keep-alive]
TRACE [ForkJoinPool.commonPool-worker-19] 14:23:46 URLLoader.doLoad(255) |  - login = [CraZZZy]
TRACE [ForkJoinPool.commonPool-worker-19] 14:23:46 URLLoader.doLoad(255) |  - Date = [Mon, 31 Jan 2022 13:23:45 GMT]
TRACE [ForkJoinPool.commonPool-worker-19] 14:23:46 URLLoader.doLoad(255) |  - sf = [ok]
TRACE [ForkJoinPool.commonPool-worker-19] 14:23:46 URLLoader.doLoad(255) |  - Cache-Control = [max-age=0, must-revalidate, private]
TRACE [ForkJoinPool.commonPool-worker-19] 14:23:46 URLLoader.doLoad(255) |  - v = [/js/sw.js?v=506bcc]
TRACE [ForkJoinPool.commonPool-worker-19] 14:23:46 URLLoader.doLoad(255) |  - Set-Cookie = [KaroSitzung=u6gl31pcgtprqgh2v4p8kvshdh; expires=Wed, 02-Feb-2022 13:23:45 GMT; Max-Age=172800; path=/; secure; httponly; samesite=none]
TRACE [ForkJoinPool.commonPool-worker-19] 14:23:46 URLLoader.doLoad(255) |  - Expires = [Mon, 31 Jan 2022 13:23:45 GMT]
TRACE [ForkJoinPool.commonPool-worker-19] 14:23:46 URLLoader.doLoad(255) |  - Content-Type = [application/json]
TRACE [ForkJoinPool.commonPool-worker-19] 14:23:46 URLLoader.doLoad(256) |  = {"id":3645,"user_id":2241,"user_name":"CraZZZy","contact_id":1411,"contact_name":"ultimate","ts":1643635425,"r":0,"text":"Hallo ultimate, das ist ein API-Test!","rxtx":"tx"}

### Auch die andere Richtung ist mit ASCII ist kein Problem (ultimate schickt Nachricht an CraZZZy)

> DEBUG [ForkJoinPool.commonPool-worker-19] 14:31:29 URLLoader.doLoad(226) | POST https://www.karopapier.de/api/messages/2241 -> {"text":"Danke"}
TRACE [ForkJoinPool.commonPool-worker-19] 14:31:29 URLLoader.doLoad(228) |  - X-Auth-Login = [ultimate]
TRACE [ForkJoinPool.commonPool-worker-19] 14:31:29 URLLoader.doLoad(228) |  - X-Auth-Password = [*********]
TRACE [ForkJoinPool.commonPool-worker-19] 14:31:29 URLLoader.doLoad(228) |  - Content-Type = [application/json; charset=utf-8]
DEBUG [ForkJoinPool.commonPool-worker-19] 14:31:29 URLLoader.doLoad(253) | POST https://www.karopapier.de/api/messages/2241 = 200 OK
TRACE [ForkJoinPool.commonPool-worker-19] 14:31:29 URLLoader.doLoad(255) |  - Transfer-Encoding = [chunked]
TRACE [ForkJoinPool.commonPool-worker-19] 14:31:29 URLLoader.doLoad(255) |  - null = [HTTP/1.1 200 OK]
TRACE [ForkJoinPool.commonPool-worker-19] 14:31:29 URLLoader.doLoad(255) |  - sw = [/js/app.js?v=29839b]
TRACE [ForkJoinPool.commonPool-worker-19] 14:31:29 URLLoader.doLoad(255) |  - Server = [nginx/1.14.0 (Ubuntu)]
TRACE [ForkJoinPool.commonPool-worker-19] 14:31:29 URLLoader.doLoad(255) |  - Connection = [keep-alive]
TRACE [ForkJoinPool.commonPool-worker-19] 14:31:29 URLLoader.doLoad(255) |  - login = [ultimate]
TRACE [ForkJoinPool.commonPool-worker-19] 14:31:29 URLLoader.doLoad(255) |  - Date = [Mon, 31 Jan 2022 13:31:29 GMT]
TRACE [ForkJoinPool.commonPool-worker-19] 14:31:29 URLLoader.doLoad(255) |  - sf = [ok]
TRACE [ForkJoinPool.commonPool-worker-19] 14:31:29 URLLoader.doLoad(255) |  - Cache-Control = [max-age=0, must-revalidate, private]
TRACE [ForkJoinPool.commonPool-worker-19] 14:31:29 URLLoader.doLoad(255) |  - v = [/js/sw.js?v=506bcc]
TRACE [ForkJoinPool.commonPool-worker-19] 14:31:29 URLLoader.doLoad(255) |  - Set-Cookie = [KaroSitzung=ojg2bictcjnheq7u17ofih5csi; expires=Wed, 02-Feb-2022 13:31:29 GMT; Max-Age=172800; path=/; secure; httponly; samesite=none]
TRACE [ForkJoinPool.commonPool-worker-19] 14:31:29 URLLoader.doLoad(255) |  - Expires = [Mon, 31 Jan 2022 13:31:29 GMT]
TRACE [ForkJoinPool.commonPool-worker-19] 14:31:29 URLLoader.doLoad(255) |  - Content-Type = [application/json]
TRACE [ForkJoinPool.commonPool-worker-19] 14:31:29 URLLoader.doLoad(256) |  = {"id":3655,"user_id":1411,"user_name":"ultimate","contact_id":2241,"contact_name":"CraZZZy","ts":1643635889,"r":0,"text":"Danke","rxtx":"tx"}

### Wenn ich aber den Text ändere und er Unicode-Zeichen enthält kriege ich ein HTTP 400 

> DEBUG [ForkJoinPool.commonPool-worker-19] 14:27:12 URLLoader.doLoad(226) | POST https://www.karopapier.de/api/messages/2241 -> {"text":"Danke und Gruß zurück!"}
TRACE [ForkJoinPool.commonPool-worker-19] 14:27:12 URLLoader.doLoad(228) |  - X-Auth-Login = [ultimate]
TRACE [ForkJoinPool.commonPool-worker-19] 14:27:12 URLLoader.doLoad(228) |  - X-Auth-Password = [*********]
TRACE [ForkJoinPool.commonPool-worker-19] 14:27:12 URLLoader.doLoad(228) |  - Content-Type = [application/json; charset=utf-8]
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 400 for URL: https://www.karopapier.de/api/messages/2241
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2069)
	at ultimate.karoapi4j.KaroAPITest.test_multiInstanceAndMessaging(KaroAPITest.java:693)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:95)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:91)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:60)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 400 for URL: https://www.karopapier.de/api/messages/2241
	at ultimate.karoapi4j.utils.URLLoader$BackgroundLoader.get(URLLoader.java:577)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://www.karopapier.de/api/messages/2241
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1985)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at ultimate.karoapi4j.utils.URLLoader.doLoad(URLLoader.java:240)
	at ultimate.karoapi4j.utils.URLLoader$BackgroundLoader.call(URLLoader.java:553)
	at ultimate.karoapi4j.utils.URLLoader$BackgroundLoader.get(URLLoader.java:573)
	... 7 more

### Siehe auch

[trace.txt](https://github.com/ultimate/KaroToolsCollection/files/7971081/trace.txt)

**Comment by ultimate** [comment]
### Wrong
```
PrintWriter out = new PrintWriter(connection.getOutputStream());
out.print(output);
out.close();
```

### Correct
```
byte[] bytes = output.getBytes(Charset.forName("UTF-8"));
connection.getOutputStream().write(bytes);
connection.getOutputStream().flush();
connection.getOutputStream().close();
```
